### ISSUE TITLE
configure: autodetect the Distro for which we are building

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#103]
And set sane defaults for thoses accordingly:

- [x] `--unitdir`: handled through `pkg-conf`
- [x] `--generatordir`: handled through `pkg-conf`
- [ ] `--statedir`
    * Arch: `/var/spool/cron/`
    * Debian: `/var/spool/cron/crontabs/` (managed by `cron-daemon-common`)
    * Fedora: ?
    * Gentoo: `/var/spool/cron/crontabs/` (has `sys-process/cronbase`)
- [ ] `--enable-boot`
    * Arch: yes
    * Debian: no
    * Fedora: ?
    * Gentoo: (optional)
- [x]  `--crond2timer`
- [x]  `--part2timer`
- [x]  user creation for **mail_on_failure**: sysusers.d snippet
- [ ]  group creation for **setgid helper**: it's a bit of a mess, some open code (the Arch-only chmod in **Makefile.in**), the sysusers.d snippets lying around upstream & downstream; maybe Debian `cron-daemon-common` needs some change too https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049353

**Comment by nabijaczleweli** [comment]
I'm actually kinda crazy and kinda insane and I think we should provide *no* distribution-specific configuration by default, *including* moving the CRON2TIMER and PART2TIMER values to, say, `--cron2timer=header.h --part2timer=header.h` or `--timer-override-dir=debian/timers`+`debian/timers/cron2timer.h`+`debian/timers/part2timer.h` and putting that in the package.

Embedding distribution-specific configuration upstream makes little sense if it's just a path (statedir) or a boolean (enable-boot), and even *less* sense when it depends on the distribution's 20 years of history of distributing cronjobs and 10 of distributing systemd units.

**Comment by a-detiste** [comment]
It's not crazy .... it's cleaner.

> CRON2TIMER and PART2TIMER
>
My comment at the top of the code says "# this is dumb, but gets the job
done".

Maybe juste some shell script that turn an easy format
like .csv, or just "value whitespace value" into the epected .hpp format
for the convenience of the packagers.

**Comment by a-detiste** [comment]
closing and moving the usefull part in `contrib/census.txt`
