### ISSUE TITLE
feature parity with Cronie: --test, --version and color in --list

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#107]
- [x] `--version`
- [x] #126
- [x] colour output

`-T | --test` and `-V | --version` are nice.
(weird clustering/selinux stuff don't belong in this simple tool)

The syntax highlighting of `crontab -l` is actually pretty minimal.
It only print the comments in blue, like **nano** does.

**vim** does more fancy stuff, but the default theme is ugly

```
tchet@antec:~$ crontab-cronie -h
crontab-cronie : option invalide -- 'h'
crontab-cronie: usage error: unrecognized option
Usage:
 crontab-cronie [options] file
 crontab-cronie [options]
 crontab-cronie -n [hostname]

Options:
 -u <user>  define user
 -e         edit user's crontab
 -l         list user's crontab
 -r         delete user's crontab
 -i         prompt before deleting
 -n <host>  set host in cluster to run users' crontabs
 -c         get host in cluster to run users' crontabs
 -T <file>  test a crontab file syntax
 -s         selinux context
 -V         print version and exit
 -x <mask>  enable debugging

Default operation is replace, per 1003.2
```

**Comment by a-detiste** [comment]
Release 1.5.7

crontab: switch off colors if NO_COLOR is set

**Comment by nabijaczleweli** [comment]
hm, if all you want is simple colouring on comments then that's easy enough to do by writing to `tmpfile()` and then reading back line-by-line. remember to respect NO_COLOR=1 (https://no-color.org/, as you noted) as well as when $TERM doesn't end in "color" (so for TERM=dumb but also actual teletypes with no colour support) please

**Comment by a-detiste** [comment]
I just want to toy a bit with this, but I don't know why I would need a `tmpfile` ...I could just do it on the fly.

**Comment by nabijaczleweli** [comment]
i suppose stringing up a pipe wouldn't be too much more complicated, yeah

**Comment by a-detiste** [comment]
> hm, if all you want is simple colouring on comments then that's easy enough to do by copy_FILE()/dup2() to tmpfile() and then reading back line-by-line instead of going directly to stdout

`edit()` is extra long, I tried to factor out a generic `read()`
