### ISSUE TITLE
cron-update should probably delete commented or deleted lines in crontab file

### ISSUE THREAD

**Issue by Beethoven-n** [systemd-cron/systemd-cron#116]
commenting lines out and doing `systemctl status cron-$USER*` results in errors like:
`Sep 07 18:52:56 laika systemd[1]: cron-dogbold-dogbold-73809f7e6c29083f5f13e61ceee934b7.timer: Unit to trigger vanished.`

when really there shouldn't be a service or timer there anymore

**Comment by nabijaczleweli** [comment]
It does delete them and they are fully gone. You can reset-failed at your leisure if you feel like you don't care about them anymore.

**Comment by Beethoven-n** [comment]
that should be in the cron-update service then, lemme see if i can add that

**Comment by Beethoven-n** [comment]
yeah adding it to the service with `systemctl edit` does actually do the expected behavior. should i do a PR or something about it?

**Comment by nabijaczleweli** [comment]
no, and it shouldn't, since it destroys system state
