### ISSUE TITLE
regression: cron-mail should be dynamically instantiated ( %i )

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#118]
```
tchet@brix ~/git/systemd-cron $ systemctl cat cron-melanie-melanie-0.service 
# /run/systemd/generator/cron-melanie-melanie-0.service
[Unit]
Description=[Cron] "17-42/5 * * * * true"
Documentation=man:systemd-crontab-generator(8)
SourcePath=/var/spool/cron/crontabs/melanie
OnFailure=cron-mail@cron\x2dmelanie\x2dmelanie\x2d0.service
OnSuccess=cron-mail@cron\x2dmelanie\x2dmelanie\x2d0\x20nonempty.service
Requires=systemd-user-sessions.service
RequiresMountsFor=/home/melanie

[Service]
Type=oneshot
IgnoreSIGPIPE=false
KillMode=process
ExecStart=/usr/bin/true
User=melanie
tchet@brix ~/git/systemd-cron $ crontab --version
2.1.0-1
```

```
tchet@antec:~$ systemctl cat cron-daily-apt-cacher-ng.service 
# /run/systemd/generator/cron-daily-apt-cacher-ng.service
[Unit]
Description=[Cron] "/etc/cron.daily/apt-cacher-ng"
Documentation=man:systemd-crontab-generator(8)
SourcePath=/etc/cron.daily/apt-cacher-ng
OnFailure=cron-failure@%i.service

[Service]
Type=oneshot
IgnoreSIGPIPE=false
KillMode=process
ExecStart=/etc/cron.daily/apt-cacher-ng
User=root
tchet@antec:~$ crontab --version
2.0.2-1
```

```
Invalid unit name "cron-melanie-melanie-0 nonempty" escaped as "cron-melanie-melanie-0\x20nonempty" (maybe you should use systemd-escape?).
Unit cron-melanie-melanie-0\x20nonempty.service could not be found.
Invalid unit name "cron-melanie-melanie-0 nonempty" escaped as "cron-melanie-melanie-0\x20nonempty" (maybe you should use systemd-escape?).
-- No entries --
```

**Comment by nabijaczleweli** [comment]
`%i` is illegal in non-template units *anyway* (why it worked is beyond me, i think it's by accident)

We can't do it *anyway* because we need the unit name to be escaped so we can unescape it correctly:
```
$ systemd-escape -u 'cron-mail@cron\x2dmelanie\x2dmelanie\x2d0.service' 'cron-mail@cron\x2dmelanie\x2dmelanie\x2d0\x20nonempty.service'
cron/mail@cron-melanie-melanie-0.service cron/mail@cron-melanie-melanie-0 nonempty.service
$ systemd-escape -u 'cron-mail@cron-melanie-melanie-0.service' 'cron-mail@cron-melanie-melanie-0\x20nonempty.service'
cron/mail@cron/melanie/melanie/0.service cron/mail@cron/melanie/melanie/0 nonempty.service
```

Why would it matter that we instantiate the template by name explicitly instead of by name systemd generates with %i?

**Comment by nabijaczleweli** [comment]
(This reads to me like you're just confused by a wrong mental model of how template units work btw. I recommend a re-read of systemd.unit(5) DESCRIPTION, paragraph starting "As mentioned above,")

**Comment by a-detiste** [comment]
1) after `dpkg -i ...deb` I'm getting flooded by error emails:

![image](https://github.com/systemd-cron/systemd-cron/assets/7994192/da17ec99-ee87-4f1d-92f8-2d5bed8f32fc)

2) usage of `%i`: the mantra is to do the absolute minimum and let `systemd` do the rest.

3) `cron-mail@.service` is a templated unit of course ...

couldn't the email parameters by re-reread from the environment (like MAILTO=) ?

**Comment by a-detiste** [comment]
4. `%i` is more readable

**Comment by a-detiste** [comment]
> unit="$1"; shift

systemd seems to do no splitting on ` ` and shipping everything in $1

**Comment by nabijaczleweli** [comment]
Yes, you merged and released before I had a chance to fully test this on my system! I would've caught this if you gave me some more time to test. I forgot systemd unescapes `%I` as one word even if it has spaces.

The mantra should also include "don't depend on unspecified undocumented behaviour". `%i` and `%I` are *not valid* in non-template units:
```
       │"%i"      │ Instance name                           │ For instantiated units this is the string  │
       │          │                                         │ between the first "@" character and the    │
       │          │                                         │ type suffix. Empty for non-instantiated    │
       │          │                                         │ units.                                     │
       ├──────────┼─────────────────────────────────────────┼────────────────────────────────────────────┤
       │"%I"      │ Unescaped instance name                 │ Same as "%i", but with escaping undone.    │
```

Hell, we were depending on a systemd bug all this time! They should've been empty!

They could be, but shouldn't, unless we want to inject even more environment variables into every job. These are `CRON_`-prefixed and should not affect the job's environment.

We could use `%N` and do a different type of parsing in mail_for_job, or we could do
```ini
ExecStart=/bin/sh -c 'exec @libexecdir@/systemd-cron/mail_for_job %I'
```
but at that point just update the parsing.

Again, I would've caught this and arrived at this conclusion if you'd waited until I tested this locally :v

**Comment by a-detiste** [comment]
It's ok ... nobody will install this package from Debian experimental and I found other bugs there.
Don't worry

**Comment by a-detiste** [comment]
> Hell, we were depending on a systemd bug all this time! They should've been empty!

`%i

**Comment by nabijaczleweli** [comment]
Actually, just tested, apparently `%i` and `%I` *are* empty in non-template units in /etc! That they ever worked must be some quirk of how systemd unescapes these.

**Comment by a-detiste** [comment]
The implementation is simpler than the documentation:

> https://github.com/systemd/systemd/blob/93f1da45566d064f4f053b37bbac2813631f58b1/src/core/unit-printf.c#L167

**Comment by a-detiste** [comment]
This behaviour is relied-on in other generators:

https://github.com/systemd/systemd/blob/93f1da45566d064f4f053b37bbac2813631f58b1/src/shared/generator.c#L508

**Comment by nabijaczleweli** [comment]
Yes, and `->instance` should also be NULL here, like it is when you put this unit into `/etc`, but isn't.

The generator link generates into `unit_name_from_path_instance("systemd-mkswap", node, ".service", &unit);` which is `systemd-mkswap@dev-sda.service`, which has an `@` in it.

**Comment by a-detiste** [comment]
> Unit files may contain additional options on top of those listed here. If systemd encounters an
> unknown option, it will write a warning log message but continue loading the unit. If an option or
> section name is prefixed with <option>X-</option>, it is ignored completely by systemd.

This can be used to pass arround the 2 parameters

https://github.com/systemd/systemd/commit/382586894b9c09974aa734a1f77d3f6f69126d76

**Comment by nabijaczleweli** [comment]
How about #119? We generate `OnSuccess=cron-mail@%n:nonempty:nometadata.service` which I think is pretty nice.

**Comment by a-detiste** [comment]
BTW when I got this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040685
that cites _per the man page_, my first reaction was to complain that the man page
doesn't/didn't mean that, but then I realised this expected behaviour just made more sense.
No need to rush.

**Comment by nabijaczleweli** [comment]
(FTR: I strongly prefer the "generate the parameters" approach over "write and parse x- fields" approach since this lets the administrator have much finer control over the behaviour (nometadata only for success or nonempty for error), and I have a few units I'd like to tune like this.)

**Comment by a-detiste** [comment]
But each generated `.service` would have had it's independant X- fields ...

**Comment by a-detiste** [comment]
Ha ok, there's a 2 x 2 matrix of parameter x mode OnSuccess/OnFailure
