### ISSUE TITLE
Notes on "multiple trigger source candidates" warning/re-parsing the systemd state in cron-mail@

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd-cron/systemd-cron#120]
In testing I just got
```
2023-09-09T15:05:42+0200 tarta systemd[1]: cron-mail@cron-nabijaczleweli-nabijaczleweli-1.service:nometadata.service: multiple trigger source candidates for exit status propagation (cron-nabijaczleweli-nabijaczleweli-1.service, cron-nabijaczleweli-nabijaczleweli-1.service), skipping.
```
I had
```
OnSuccess=cron-mail@cron-nabijaczleweli-nabijaczleweli-1.service:nometadata.service
OnFailure=cron-mail@cron-nabijaczleweli-nabijaczleweli-1.service:nometadata.service
```

Adding
```
ExecStartPre=/bin/sh -c 'set | grep MONITOR_'
```
to cron-mail@ I got
```
2023-09-09T15:06:34+0200 tarta sh[819555]: MONITOR_EXIT_CODE='exited'
2023-09-09T15:06:34+0200 tarta sh[819555]: MONITOR_EXIT_STATUS='0'
2023-09-09T15:06:34+0200 tarta sh[819555]: MONITOR_INVOCATION_ID='fcce2cf2a657420e9913c533aebda51f'
2023-09-09T15:06:34+0200 tarta sh[819555]: MONITOR_SERVICE_RESULT='success'
2023-09-09T15:06:34+0200 tarta sh[819555]: MONITOR_UNIT='cron-nabijaczleweli-nabijaczleweli-1.service'
```

Notably, we already do
```
systemctl show --property=User --property=Environment --property=ActiveState --property=InvocationID "$unit"
```
but we could only reduce it to
```
systemctl show --property=User --property=Environment --property=ActiveState "$unit"
```
so this isn't all that great, and we'd require a super-fresh systemd (12ba65964f1849a043db42871ccbcb522bc73575) and it'd complicate tests.

We should probably just generate
```
OnSuccess=cron-mail@cron-nabijaczleweli-nabijaczleweli-1.service:Success:nometadata.service
OnFailure=cron-mail@cron-nabijaczleweli-nabijaczleweli-1.service:Failure:nometadata.service
```
to silence the warning.

It appears impossible to silence the warning otherwise.

**Comment by a-detiste** [comment]
so want/can release ?

**Comment by a-detiste** [comment]
I'll test too with a private build

**Comment by nabijaczleweli** [comment]
Just found c1101c921da79221165e0382ab8d6e67c2d984e9, but looks fine to me.

**Comment by nabijaczleweli** [comment]
Just found c1101c921da79221165e0382ab8d6e67c2d984e9, but looks fine to me; wrote NEWS with the good news at https://salsa.debian.org/detiste-guest/systemd-cron/-/merge_requests/9

**Comment by a-detiste** [comment]
OK ... I almost want to install Vixie-cron to see what it's mails looks like.

Usability quirks:

Title: [brix] job cron-melanie-melanie-0.service output

Should it be the unmangland original name ( /var/spool/cron/crontabs/melanie + something ) ?

---

The `check-dfsg-status` case: this thing expect the `CRON_MAIL_FORMAT=nometadata`.

Should we have yet an other heuristic table in debian package to set it automaticaly ?

Or can there be some kind of protocol to let us know that this package expect this behaviour ?

**Comment by a-detiste** [comment]
check-dfsg-status: I add it now.

**Comment by nabijaczleweli** [comment]
I don't see how it does, or how it's relevant.
```
$ usr/bin/check-dfsg-status --reason-dir=usr/share/check-dfsg-status/reasons
               Non-free packages installed on tarta

firmware-bnx2                       Binary firmware for Broadcom NetXtremeII
intel-microcode                     Processor microcode firmware for Intel CPUs
manpages-posix                      Manual pages about using POSIX system
manpages-posix-dev                  Manual pages about using a POSIX system for developmen
p7zip-rar                           non-free rar module for p7zip
snmp-mibs-downloader                install and manage Management Information Base (MIB) f
unrar                               Unarchiver for .rar files (non-free version)
  Reason: Modifications problematic

                Contrib packages installed on tarta

libnvpair3linux                     Solaris name-value library for Linux
libuutil3linux                      Solaris userland utility library for Linux
libzfs4linux                        OpenZFS filesystem library for Linux - general support
libzpool5linux                      OpenZFS pool library for Linux
zfs-dkms                            OpenZFS filesystem kernel modules for Linux
zfs-dracut                          OpenZFS root filesystem capabilities for Linux - dracu
zfs-zed                             OpenZFS Event Daemon
zfsutils-linux                      command-line tools to manage OpenZFS filesystems

  7 non-free packages, 0.4% of 1665 installed packages.
  8 contrib packages, 0.5% of 1665 installed packages.
```

..... so? it's just output, there's nothing special here? it behaves correctly? sounds like a fake issue to me:

![](https://github.com/systemd-cron/systemd-cron/assets/6709544/85b99616-d501-4613-b18b-f55e16e94986)

**Comment by nabijaczleweli** [comment]
If check-dfsg-status maintainers want to configure their output specially, they can ship `/lib/systemd/system/cron-monthly-check-dfsg-status.service.d/alwaysmail.conf` that says

```ini
[Unit]
OnSuccess=
OnSuccess=cron-mail@%n:Success:nonempty:nometadata.service
```

That we have a list of overrides for cron.{daily,...} names is already stupid, but unavoidable. Adding another bit of "oh please please please add our package to your overrides list!!!!!!" is insane. Just ship Your Preferred Config.

**Comment by nabijaczleweli** [comment]
ESPECIALLY since this violates the user's configuration. This is just insane. We can't ship this.

**Comment by nabijaczleweli** [comment]
As for service names in the subject: sure, we could parse SourcePath=. We probably don't want to use SourcePath= directly, since "/var/spool/cron/crontabs/nabijaczleweli job 0" is worse than "cron-nabijaczleweli-nabijaczleweli-0.service", but we could do some light parsing to make the output better.

**Comment by a-detiste** [comment]
> /lib/systemd/system/cron-monthly-check-dfsg-status.service.d/alwaysmail.conf 

that is a good idea ... it's not so intrusive to beg packages to support it.

**Comment by a-detiste** [comment]
Yup maybe it's too little too late to mess with this.

[check-dfsg-status](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1026287)

**Comment by a-detiste** [comment]
This could go in the NEWS file.

```
If check-dfsg-status maintainers want to configure their output specially, they can ship /lib/systemd/system/cron-monthly-check-dfsg-status.service.d/alwaysmail.conf that says

[Unit]
OnSuccess=
OnSuccess=cron-mail@%n:Success:nonempty:nometadata.service
```

**Comment by a-detiste** [comment]
It' serious.

Release now the upstream part ?

**Comment by nabijaczleweli** [comment]
Sure, passes all my tests and behaves sanely for me.

I can tune up the subjects later, I already have a nice idea.

**Comment by a-detiste** [comment]
one final thing, maybe I did something dumb, but OnSuccess doesn't get reseted

```
tchet@brix ~/git/systemd-cron $ systemctl cat cron-monthly-check-dfsg-status.service
# /run/systemd/generator/cron-monthly-check-dfsg-status.service
[Unit]
Description=[Cron] "/etc/cron.monthly/check-dfsg-status"
Documentation=man:systemd-crontab-generator(8)
SourcePath=/etc/cron.monthly/check-dfsg-status
OnFailure=cron-mail@%n:Failure.service
OnSuccess=cron-mail@%n:Success:nonempty.service

[Service]
Type=oneshot
IgnoreSIGPIPE=false
KillMode=process
ExecStart=/etc/cron.monthly/check-dfsg-status
Environment=MAILTO=alexandre.detiste@gmail.com
User=root

# /usr/lib/systemd/system/cron-monthly-check-dfsg-status.service.d/alwaysmail.conf
[Unit]
OnSuccess=
OnSuccess=cron-mail@%n:Success:nonempty:nometadata.service

tchet@brix ~/git/systemd-cron $ systemctl show  cron-monthly-check-dfsg-status.service | grep On
OnSuccess=cron-mail@cron-monthly-check-dfsg-status.service:Success:nonempty.service cron-mail@cron-monthly-check-dfsg-status.service:Success:nonempty:nometadata.service
OnFailure=cron-mail@cron-monthly-check-dfsg-status.service:Failure.service
OnSuccessJobMode=fail
OnFailureJobMode=replace
```

**Comment by a-detiste** [comment]
https://superuser.com/questions/1539971/systemd-drop-ins-wont-override-specific-values

**Comment by nabijaczleweli** [comment]
```
       OnFailure=
           A space-separated list of one or more units that are activated when this unit enters the "failed" state.

       OnSuccess=
           A space-separated list of one or more units that are activated when this unit enters the "inactive" state.
```
doesn't explicitly say that these can be reset, so maybe it just can't be reset. I'd assumed you could.
Blame Lennart.

Maybe you just can't override this, and can only append. Annoying. But considering these are user's preferences – which are already configured in `/etc/crontab` – I don't really feel like this is much of an issue that a package can't override them? A user can always do `edit --full` if they want a non-additive configuration (since you very much can do, for example,
```
[Unit]
OnSuccess=cron-mail@%n:nonempty:Success.service
```
to enable on-success mailing for a specific unit if you have it disabled globally, which I think is the 99% config).

**Comment by a-detiste** [comment]
https://salsa.debian.org/detiste-guest/systemd-cron/-/jobs/4679188 I need a beer

**Comment by nabijaczleweli** [comment]
Can repro locally (well, `sudo autopkgtest -- lxc autopkgtest-sid.new` "locally"), let's see.

**Comment by nabijaczleweli** [comment]
Oh, of course:
```
Breakpoint 1, Job::generate_service (this=0x7fffffffe700, into=0x555555581d20) at ./src/bin/systemd-crontab-generator.cpp:700
700             auto generate_service(FILE * into) -> void {
(gdb) p HAS_SENDMAIL
$1 = false
```

**Comment by nabijaczleweli** [comment]
d1302dc37729066e2d6331be2c8c6af74aaf52a4

(also, do we want to revert 9b0e529461c2ececa56091aaf8282f2baa24c4a8?)
