### ISSUE TITLE
~ operator

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#135]
this looks cute

https://github.com/cronie-crond/cronie/issues/85

not backward compatible with Vixie cron of course

**Comment by nabijaczleweli** [comment]
"Cute" is not a good reason to import random garbage. That said, hidden well in https://github.com/cronie-crond/cronie/pull/95/files, it says "The random number is picked when crontab file is parsed." so it is, uh. Implementable. Whether we *should* is another question: Are people actually using this? Is anyone actually using this? Is there a de-facto standard?
Unclear what this "cronie" is, since it's not in debian, so one has to assume "no users". A quick look at manpages.d.o crontab.5, searching for "~", it's not in bcron, cron, or sd-cron. It's not in NetBSD or FreeBSD, but it is in OpenBSD.

**Comment by a-detiste** [comment]
Systemd would do the randomization  `RandomizedDelaySec= end - start` ...

cronie is RedHat's cron (-fork) and is well pretty used / documented / supported.

The rough plan for Debian was to switch to cronie as default cron-daemon,
but I think that with all these cronjobs only doing `test -d /run/systemd && exit 0` 
it's now too little too late anyway.

But if cronie were to become the default systemd-cron would had to be compatible.

**Comment by a-detiste** [comment]
The question is more `When` than `Whether` ... so when someone will complain.

Like Sunday = 7, it's not standard but supported somewhere somehow.

Some websites like https://manpages.ubuntu.com/ are particularly
unhelpfull because they will pick one of the `cron-daemon`
manpages at random...

https://manpages.ubuntu.com/manpages/focal/en/man5/crontab.5.html -> systemd-cron
https://manpages.ubuntu.com/manpages/jammy/en/man5/crontab.5.html -> bcron
https://manpages.ubuntu.com/manpages/lunar/en/man5/crontab.5.html -> cron

**Comment by nabijaczleweli** [comment]
ubuntu user error v0v

anyway, easy enough
``
$ for in in $(seq 1000); do out/build/bin/systemd-crontab-generator --translate '~ * * * * :' 3>&1 4>/dev/null ; done | grep OnCalendar | sort | uniq -c
     33 OnCalendar=*-*-* *:0:00
     15 OnCalendar=*-*-* *:1:00
     19 OnCalendar=*-*-* *:10:00
     22 OnCalendar=*-*-* *:11:00
     16 OnCalendar=*-*-* *:12:00
     14 OnCalendar=*-*-* *:13:00
     15 OnCalendar=*-*-* *:14:00
     15 OnCalendar=*-*-* *:15:00
     17 OnCalendar=*-*-* *:16:00
     13 OnCalendar=*-*-* *:17:00
     16 OnCalendar=*-*-* *:18:00
     21 OnCalendar=*-*-* *:19:00
     15 OnCalendar=*-*-* *:2:00
     18 OnCalendar=*-*-* *:20:00
     23 OnCalendar=*-*-* *:21:00
     18 OnCalendar=*-*-* *:22:00
     12 OnCalendar=*-*-* *:23:00
     17 OnCalendar=*-*-* *:24:00
     17 OnCalendar=*-*-* *:25:00
     16 OnCalendar=*-*-* *:26:00
     15 OnCalendar=*-*-* *:27:00
     14 OnCalendar=*-*-* *:28:00
     15 OnCalendar=*-*-* *:29:00
     21 OnCalendar=*-*-* *:3:00
     14 OnCalendar=*-*-* *:30:00
     16 OnCalendar=*-*-* *:31:00
     15 OnCalendar=*-*-* *:32:00
     16 OnCalendar=*-*-* *:33:00
     18 OnCalendar=*-*-* *:34:00
     13 OnCalendar=*-*-* *:35:00
     20 OnCalendar=*-*-* *:36:00
     18 OnCalendar=*-*-* *:37:00
     13 OnCalendar=*-*-* *:38:00
      8 OnCalendar=*-*-* *:39:00
     12 OnCalendar=*-*-* *:4:00
     18 OnCalendar=*-*-* *:40:00
     14 OnCalendar=*-*-* *:41:00
     20 OnCalendar=*-*-* *:42:00
     19 OnCalendar=*-*-* *:43:00
     21 OnCalendar=*-*-* *:44:00
      9 OnCalendar=*-*-* *:45:00
      9 OnCalendar=*-*-* *:46:00
     19 OnCalendar=*-*-* *:47:00
     17 OnCalendar=*-*-* *:48:00
     19 OnCalendar=*-*-* *:49:00
     13 OnCalendar=*-*-* *:5:00
     10 OnCalendar=*-*-* *:50:00
     14 OnCalendar=*-*-* *:51:00
     23 OnCalendar=*-*-* *:52:00
     21 OnCalendar=*-*-* *:53:00
     17 OnCalendar=*-*-* *:54:00
     15 OnCalendar=*-*-* *:55:00
     19 OnCalendar=*-*-* *:56:00
     12 OnCalendar=*-*-* *:57:00
     22 OnCalendar=*-*-* *:58:00
     12 OnCalendar=*-*-* *:59:00
     21 OnCalendar=*-*-* *:6:00
     19 OnCalendar=*-*-* *:7:00
     21 OnCalendar=*-*-* *:8:00
     16 OnCalendar=*-*-* *:9:00
```

**Comment by a-detiste** [comment]
> random garbage

In my view Sun=7 was 'garbage' ... non POSIX ... but I did it anyway, ... and you said you like it better...

It's more like a mater of acquired taste ...

**Comment by a-detiste** [comment]
> "The random number is picked when crontab file is parsed." 

This is an impletation detail in `cronie`.
It's better to have reproducible `.timer` files (and there's the md5 thing)

**Comment by nabijaczleweli** [comment]
Nope, that's the standard defined by OpenBSD and only copied by cronie. AFAICT systemd has no way to represent this anyway.

**Comment by a-detiste** [comment]
I though of changing random_delay to a string to accept both hour & minutes.

Other units don't really make sense (?)

```
b/src/bin/systemd-crontab-generator.cpp
@@ -140,7 +140,7 @@ struct Job {
        std::map<std::string_view, std::string_view> environment;
        std::string environment_PATH_storage;  // borrowed into environment on expansion
        std::string_view shell;
-       std::size_t random_delay;
+       std::string random_delay;
        std::string period;  // either period or timespec
        std::optional<std::string_view> timezone;
        std::set<std::uint8_t> timespec_minute;   // 0-60                           or TIMESPEC_ASTERISK
@@ -218,7 +218,7 @@ struct Job {
                this->shell           = "/bin/sh"sv;
                this->boot_delay      = 0;
                this->start_hour      = 0;
-               this->random_delay    = 0;
+               this->random_delay    = {};
                this->persistent      = false;
                this->user            = "root"sv;
                this->command         = {};
@@ -258,7 +258,7 @@ struct Job {
                                this->persistent = systemd_bool(v);
                        else if(k == "RANDOM_DELAY"sv) {
                                bool err{};
-                               this->random_delay = int_map(v, err);
+                               this->random_delay = int_map(v, err); //   + 'm'
                                if(err)
                                        this->log(Log::WARNING, "invalid RANDOM_DELAY");
                        } else if(k == "START_HOURS_RANGE"sv) {
@@ -443,6 +443,15 @@ struct Job {
                        base = *std::min_element(std::begin(values), std::end(values));
 
                std::set<T> result;
+
+                // if '~' in value:
+                //    START, END = value.split('~')
+                //    if field in ('hour', 'minute'
+                //       this->random_delay = str(END-START) + field[m]
+                //    else:
+                //       print warning
+                //    value = START
+
                for(auto && subval : vore::soft_tokenise{value, ","sv})  // NOTE: this glides over consecutive commas so "0,,3" is accepted as-if "0,3"
                        if(auto err = parse_period(subval, values, result, mapping, base)) {
                                if(*err)
-               if(this->random_delay > 1)
-                       std::fprintf(into, "RandomizedDelaySec=%zum\n", this->random_delay);
+               if(this->random_delay)
+                       std::fprintf(into, "RandomizedDelaySec=%zu\n", this->random_delay);
                if(this->persistent)
                        std::fputs("Persistent=true\n", into);
```

**Comment by a-detiste** [comment]
It start feeling like a bad idea :-)

**Comment by nabijaczleweli** [comment]
the most complicated part was inventing a "use the original string for hashing for persistent timers instead of the normalised regenerated output" system tbh

**Comment by a-detiste** [comment]
wow

**Comment by a-detiste** [comment]
@nabijaczleweli : this year systemd-cron was elected by manpages.ubuntu.com as "the real thing" :-)
https://manpages.ubuntu.com/manpages/noble/en/man5/crontab.5.html
