### ISSUE TITLE
generator will accept garbage timespec as '*' for minue, hour and dow fields.

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#138]
You build it, I break it (still sick at the moment)

```
/lib/systemd/system-generators/systemd-crontab-generator --translate 'This is 1 1 garbage echo test' 3>&1 4>/dev/null
```

```
/lib/systemd/system-generators/systemd-crontab-generator --translate 'This is even more garbage echo test' 3>&1 4>/dev/null
systemd-crontab-generator: -: This is even more garbage echo test: field day=even (even), may be * or [1, 31]
systemd-crontab-generator: -: This is even more garbage echo test: field month=more (more), may be * or [jan, dec] or [1, 12]
```

**Comment by a-detiste** [comment]
thanks, the part that access tz[0] _before_ checking tz.isempty() scares me because I don't know C++ enough

**Comment by nabijaczleweli** [comment]
yes, that should've been starts_with() (it's safe, since we know we always have more data past tz, but! it's nominally UB); starts_with() is for string_view is relatively new and I'm not used to it yet, so I wrote it as tz[0]; 3ad99d57708bf736c57d102b5767b2b1e1024590

**Comment by a-detiste** [comment]
I don't know if that would make `valgrind` cry or not.

**Comment by nabijaczleweli** [comment]
wouldn't

**Comment by a-detiste** [comment]
but setting back `TZ=` (to empty) is not handled in anyway

**Comment by nabijaczleweli** [comment]
Well, it is in that the variable is still passed through to the program, but we just don't do anything with it. This matches historical practice, so meh.

**Comment by a-detiste** [comment]
ha yes ! There's the `this->environment.emplace(k, v);`

**Comment by a-detiste** [comment]
maybe this, to allow setting it disabling it back later in same crontab

```
-               if(!tz.empty() && !access(("/usr/share/zoneinfo/"s += tz).c_str(), F_OK))
-                                                this->timezone = tz;
+              if(tz.empty())
+                      this->timezone = std::nullopt;
+              else if (!access(("/usr/share/zoneinfo/"s += tz).c_str(), F_OK))
+                      this->timezone = tz;
```

**Comment by nabijaczleweli** [comment]
b31f48a84f10959928e21843b6d66df0981d0b9a
