### ISSUE TITLE
run per-user crontab parsing as the UID for the user

### ISSUE THREAD

**Issue by pabs3** [systemd-cron/systemd-cron#145]
After #144 is fixed, when parsing per-user crontabs, please only run the parsing as the user that owns the crontab being parsed, not as root or a dedicated user.
This is important for security since currently if there were a bug in `systemd-crontab-generator` then it could result in the user running arbitrary code as root.

**Comment by a-detiste** [comment]
systemd-crontab-generator is run as root by systemd itself. Of course I tought of random input attack agains it to gain root; that's why we generate scriptlets in /run instead of trying to escape shell code to run through `/bin/sh -c ''`

**Comment by a-detiste** [comment]
>  not in bin/crontab

The pre-validation step is run under the user's id; and invalid crontab are rejected right away

**Comment by pabs3** [comment]
As mentioned in #144 I think not running systemd-crontab-generator
as root for users is better, especially since it could be run as a
user-generator as well as a system-generator, and that eliminates
all chances that the user could somehow cross a privilege boundary.

**Comment by pabs3** [comment]
(a) I think #144 is desirable to implement for some users.

(b) reading crontabs could be implemented via the setgid helper?

(c) AFAICT user generators run as the user and write to the generated
user units directory in /run which is owned by the user.

(d) which files are involved in formatting? 

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
