### ISSUE TITLE
escaped percent (`\%`) characters not unescaped

### ISSUE THREAD

**Issue by pabs3** [systemd-cron/systemd-cron#146]
When the crontab command to be run contains the escaped percent string `\%`, systemd-cron-generator does not unescape the percent character, which results in syntax errors when running the command and failure of the jobs.

**Comment by a-detiste** [comment]
Hi, I simply tought that nobody used this feature;

https://manpages.debian.org/unstable/systemd-cron/crontab.5.en.html#LIMITATIONS

* multi-line jobs separated by the '%' character

----

It should be possible by generating a file in /run/ to feed `StandardInput=` with
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#StandardInput=

I'm not confident in using `StandardInputText=` with unknown user-prodived data

**Comment by pabs3** [comment]
I don't use the multi-line jobs feature, but I do have to use the
percent character in some single-line jobs and with standard cron
you have to escape that and then the escaping breaks in systemd-cron.

**Comment by a-detiste** [comment]
I think it should be better/easier to implement the whole feature than to find the right wording to explain how & why it's half implemented for the LIMITATIONS paragraph.

**Comment by pabs3** [comment]
I don't think you need to update the LIMITATIONS section of the manual,
the percent-escaping is not much of a feature, but is a compat issue.

**Comment by a-detiste** [comment]
change would happen in the second half of `generate_scriptlet()`

**Comment by a-detiste** [comment]
or maybe better after it's called in `output()`

**Comment by a-detiste** [comment]
Thank you very much.

I see even French version of wikipedia recommends snippets with the `%` sign; so it might be more popular than I tought.

https://fr.wikipedia.org/wiki/Cron
```
.... something ... something ... last day of month::
 0 0 28-31 * * [ `/bin/date +\%d` -gt `/bin/date +\%d -d "1 day"` ] && df >> /tmp/df.log
```
and lots of random webpages like
https://stackoverflow.com/questions/6139189/cron-job-to-run-on-the-last-day-of-the-month
