### ISSUE TITLE
set `WorkingDirectory=~` for generated systemd service units

### ISSUE THREAD

**Issue by pabs3** [systemd-cron/systemd-cron#147]
Under standard cron, crontabs have the working directory set to `~/`.
Under systemd-cron the working directory is currently set to `/`.
This is a compatibility issue for jobs that currently refer to files using relative paths,
since they would be paths relative to the home directory instead of the root directory.
Fixing that should just be a matter of using `WorkingDirectory=~` in the generated systemd service units.

**Comment by a-detiste** [comment]
Only for the jobs in /var/spool/...

**Comment by pabs3** [comment]
Yes, the user crontabs in /var/spool are the ones I want mail output
for and that may run when I am logged out.

**Comment by a-detiste** [comment]
I tried to create a PR but commited to the wron branch ... so it's in.

**Comment by a-detiste** [comment]
I think that distribution-provided crontabs in /etc/cron.d/ might refer to users with non-existing home and I don't want to see these warnings. (and distribution-provided scripts should be more robust)

**Comment by pabs3** [comment]
Sorry for the offtopic comment, mixed up the bugs.

The cron config in /etc isn't solely shipped by distros, there could be
admin-supplied ones that rely on the working dir being set correctly.

I think the working directory should be set exactly the same in
systemd-cron as in standard cron for maximum compatibility.

From what I read in search engines, that is always $HOME.

**Comment by a-detiste** [comment]
Yes, documented in lot of places
https://cronitor.io/guides/cron-job-working-directory#fixing-problems-with-the-cron-working-directory

I think my tiny commit is a step in the obvious good direction, let's keep this discussion open.

**Comment by nabijaczleweli** [comment]
A quick test with FreeBSD cron and real Debian cron shows that the jobs behave as-if `WorkingDirectory=~` were set unconditionally, not only for user crontabs.
