### ISSUE TITLE
Non-executable files in /etc/cron.hourly, etc. should be silently ignored, when not using run-parts

### ISSUE THREAD

**Issue by albel727** [systemd-cron/systemd-cron#151]
run-parts doesn't run files that are not executable, so the user could always disable cron jobs without deleting them with `chmod -x`. But systemd-cron, when configured not to use run-parts, generates systemd units for all files present in `/etc/cron.{hourly,daily,weekly,monthly,yearly}`, which subsequently fail, when triggered by the timers, if they are pointing to files that aren't actually executable.

The generated systemd units should contain `ConditionFileIsExecutable=` directive to silently skip running non-executable files. Alternatively the units could be not generated at all, but then one couldn't re-enable cron jobs on the fly with `chmod +x`.

**Comment by nabijaczleweli** [comment]
Yes.

`chmod +x` triggers `cron-update.path` so just don't generate.
