### ISSUE TITLE
tracker for when/if this gets integrated into systemd

### ISSUE THREAD

**Issue by prometheanfire** [systemd-cron/systemd-cron#40]
Don't know if you care, but I'd like to leave this open til this will likely get merged with systemd (since we are installing stuff into FHS owned dirs and conflicts can happen).

I'm leaving this open so people can track and remove the non-tracked-by-package-manager files when needed

**Comment by a-detiste** [comment]
This will never get merged in systemd. Some use this because they prefer the crontab syntax or use it as a replacement of cron in the Debian depedency systemd; but upstream don't need/want this.

http://www.freedesktop.org/wiki/Software/systemd/Generators/
> It's often a better idea to just deprecate old stuff instead of keeping it artificially alive.

I don't understand the bit about FHS, if you build from source, you can `./configure` it the way you like.

**Comment by kstep** [comment]
Just as a side note, I already told it in rationale for kstep/systemd-crontab-generator (TLDR: there was an initiative to build proper crontab generator in C, but it was declined by Lennart himself at the prototype stage):

> The crontab generator for systemd (implemented in C) was already [published][] on maillist,
> but was later [declined][] by Lennart:

>> I am not convinced this is a really good idea. From my perspective at
least it appears that we should much rather just convert the crontabs
and that's it. Unlike sysv init scripts the number of crontab in use (at
least on Fedora) is relatively small, and very rare in third-party
packages.
>>
>> Lennart

[published]: http://lists.freedesktop.org/archives/systemd-devel/2013-August/012591.html
[declined]: http://lists.freedesktop.org/archives/systemd-devel/2013-September/013120.html

Please follow links for details on original discussion on systemd maillist.

**Comment by prometheanfire** [comment]
ah, fair enough :D

**Comment by a-detiste** [comment]
@kstep thanks, I couldn't locate this mail anymore :-) can we just copy your rationale in this repo ?

@dbent

**Comment by dbent** [comment]
FYI, the Lennart's mail is [here](http://lists.freedesktop.org/archives/systemd-devel/2013-September/013120.html).
