### ISSUE TITLE
Parse per-user crontabs in /var/spool/cron/crontabs/

### ISSUE THREAD

**Issue by mikken** [systemd-cron/systemd-cron#42]
A feature request.
In addition to /etc/crontab I'd wish that /var/spool/cron/crontabs/ was also translated into timer units.

**Comment by kstep** [comment]
What distributive uses this location?

**Comment by a-detiste** [comment]
Debian.  run './configure --statedir=/var/spool/cron/crontabs' does the trick

https://anonscm.debian.org/cgit/collab-maint/systemd-cron.git/tree/debian/rules#n5

**Comment by kstep** [comment]
FWIW, user crontabs from `/var/spool/cron` are already processed, and crontab utility works with the directory to place user crontabs to.

**Comment by kstep** [comment]
Maybe we should make state dir lookup recursive and be done with it?

**Comment by mikken** [comment]
No. no.
/var/spool/cron shouldn't be viewed recursively, it also contains cronstamps and lastrun dirs.
Previously I was using dcron and I edited my user crontab with KDE's System Settings applet.
Now I uninstalled dcron and installed systemd-cron, I'll have to test where the applet places my user crontab now.
This is Gentoo distribution and dirs under /var/spool/cron/ are contained in common "cronbase" package.

**Comment by a-detiste** [comment]
@statedir@ is also in `src/units/cron-update.path.in` & `src/man/crontab.1.in` & `src/man/systemd-crontab-generator.8.in`; I guess it's much simpler to keep this as a build option.

**Comment by a-detiste** [comment]
KDE applet is a bit dumb :cry:  , it will sort the file and put all the environment variable assignements at the top...

**Comment by a-detiste** [comment]
systemd-cron provides the same crontab interface as dcron or vixie-cron. 
KDE applet calls this `crontab` inteface.
You can also call it directly on the command line: `crontab -l` to list it or `crontab -e`.
user crontabs file location doesn't matter for the KDE applet.

**Comment by mikken** [comment]
Ok then.
