### ISSUE TITLE
use RandomizedDelaySec= on systemd >= 229

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#45]
https://github.com/systemd/systemd/commit/6f5d79986a9c98b9cacc83f865fed957e4e6e4e6

**Comment by silverhammermba** [comment]
Why is this still unfixed? It looks like a trivial change. I'd like to keep recommending this project on the Arch wiki, but not if it still uses this broken behavior.

**Comment by a-detiste** [comment]
At first I was waiting on new Debian release, then I have now a rundown house to fix... when I moved in there was a single electric socket :-) ...it's getting better now.
