### ISSUE TITLE
Allow configuration of MAILTO in mail_on_failure

### ISSUE THREAD

**Issue by Yamakaky** [systemd-cron/systemd-cron#46]

**Comment by a-detiste** [comment]
(this is missing only for the cron.hourly|daily|weekly|monthly )

**Comment by a-detiste** [comment]
I: you can use "systemctl edit" to override the Environment= instruction and set it to what pleases you.

An empty "Environment=MAILTO=" means that no e-mails are event sent :-)

Bonne soirée

**Comment by a-detiste** [comment]
Now these jobs will also inherit the default `MAILTO` from /etc/crontab
