### ISSUE TITLE
Generate units for cron.daily, cron.weekly, and cron.monthly

### ISSUE THREAD

**Issue by rlaager** [systemd-cron/systemd-cron#47]
I'm curious why systemd-cron still uses the run-parts approach for cron.daily, cron.weekly, and cron.monthly. Why not generate services & timers for those too?

This is NOT a complete solution ready-to-commit, but roughly, something like the following (plus removal of all the existing cron.daily/weekly/monthly pieces):
```
--- systemd-cron-1.5.3/src/bin/systemd-crontab-generator.py	2015-02-16 15:32:02.000000000 -0600
+++ systemd-crontab-generator	2016-12-02 16:31:51.590906662 -0600
@@ -53,7 +53,7 @@
             parts[i] = home + part[1:]
     return ':'.join(parts)
 
-def parse_crontab(filename, withuser=True, monotonic=False):
+def parse_crontab(filename, withuser=True, monotonic=False, env_only=False):
     basename = os.path.basename(filename)
     environment = { }
     random_delay = 1
@@ -96,6 +96,9 @@
                      environment[envvar.group(1)] = value
                 continue
 
+            if env_only:
+                continue
+
             parts = line.split()
             line = ' '.join(parts)
 
@@ -202,6 +205,16 @@
                             'c': command,
                             'Z': batch,
                             }
+    if env_only:
+        yield {
+                'e': ' '.join('"%s=%s"' % kv for kv in environment.items()),
+                's': environment.get('SHELL','/bin/sh'),
+                'a': random_delay,
+                'b': boot_delay,
+                'h': start_hours_range,
+                'P': False if persistent == Persistent.no else True,
+                'Z': batch,
+                }
 
 def parse_time_unit(filename, line, value, values, mapping=int):
     if value == '*':
@@ -489,6 +502,31 @@
                     continue
                 generate_timer_unit(job, seqs.setdefault(job['j']+job['u'], count()))
 
+    job_template = list(parse_crontab('/etc/crontab', env_only=True))[0]
+    job_template['P'] = False
+    job_template['u'] = 'root'
+    for period in ['daily', 'weekly', 'monthly']:
+        CRONTAB_FILES = files('/etc/cron.' + period)
+        for filename in CRONTAB_FILES:
+            job_template['p'] = period
+            basename = os.path.basename(filename)
+            if (os.path.exists('/lib/systemd/system/%s.timer' % basename)
+             or os.path.exists('/etc/systemd/system/%s.timer' % basename)):
+                log(5, 'ignoring %s because native timer is present' % filename)
+                continue
+            elif basename.startswith('.'):
+                continue
+            elif '.dpkg-' in basename:
+                log(5, 'ignoring %s' % filename)
+                continue
+            else:
+                job = job_template
+                job['l'] = filename
+                job['f'] = filename
+                job['j'] = basename
+                job['c'] = filename
+                generate_timer_unit(job, seqs.setdefault(job['j']+job['u'], count()))
+
     if os.path.isfile('/etc/anacrontab'):
         for job in parse_crontab('/etc/anacrontab', monotonic=True):
             if 'c' not in job:
```

**Comment by a-detiste** [comment]
It may be a question of taste; but the run-parts bits ensure that jobs run in a predictable, serialized, way.
(and I personaly use it for /etc/cron.dail/z.... or /etc/cron.dail/0.... jobs)

Indepent jobs would run all the the same time.

**Comment by a-detiste** [comment]
@rlaager

Well the error-handly of those daily/weekly/motnh jobs is lame.

The automated e-mail is completely useless (the error was in `apt-cacher-ng` see the mail I got !)

So I'm now reconsidering this :-)

Your code example lack a walk() or something  that does actually look-up the individual
files in /etc/cron.daily/ ... 

```
● cron-daily.service - systemd-cron daily script service
    Loaded: loaded (/etc/systemd/system/cron-daily.service; static; vendor preset: enabled)
    Active: failed (Result: exit-code) since Tue 2016-12-06 11:50:13 CET; 87ms ago
      Docs: man:systemd.cron(7)
   Process: 613 ExecStart=/bin/run-parts --report /etc/cron.daily (code=exited, status=1/FAILURE)
  Main PID: 613 (code=exited, status=1/FAILURE)

 déc 06 11:49:19 antec run-parts[613]: ... are different, keeping
 déc 06 11:49:19 antec run-parts[613]: /home/julie/Downloads/publication_749055 (1).pdf
 déc 06 11:49:19 antec run-parts[613]: and
 déc 06 11:49:19 antec run-parts[613]: /home/julie/Downloads/publication_749055.pdf
 déc 06 11:49:19 antec run-parts[613]: ... are different, keeping
 déc 06 11:50:13 antec systemd[1]: cron-daily.service: Main process exited, code=exited, status=1/FAILURE
 déc 06 11:50:13 antec systemd[1]: Failed to start systemd-cron daily script service.
 déc 06 11:50:13 antec systemd[1]: cron-daily.service: Unit entered failed state.
 déc 06 11:50:13 antec systemd[1]: cron-daily.service: Triggering OnFailure= dependencies.
 déc 06 11:50:13 antec systemd[1]: cron-daily.service: Failed with result 'exit-code'.
```

**Comment by a-detiste** [comment]
saw "files()" now

**Comment by rlaager** [comment]
Yeah, this is just something I whipped up quickly to see about building the units. I'm not sure if I love the way I used the environment variable parsing code for crontab; maybe that should be refactored. And I'm sure there are plenty of other little issues to sort through before this is production ready, not the least of which is compatibility with existing installations.

**Comment by Zugschlus** [comment]
Debian is currently having this discussion on debian-devel, see Thread starting with https://lists.debian.org/debian-devel/2019/07/msg00517.html

How about having a configuration option whether to use run-parts or to generate individual timer units?

Debian is also discussing the advantages and disadvantages of having all cron.fooly jobs running serialized, randomized or in parallel. Serialization and Randomization has advantages in virtualized environments, avoiding the load spike that happens when a gazillion of VMs run their cron.fooly jobs in parallel, while on a laptop, having them run in parallel is more efficient since that would allow the machine to return to power-save idle faster. So it would be (this is where my personal opinion begins) an advantage to have this configurable.

Greetings
Marc

**Comment by a-detiste** [comment]
Hi,

Indeed Im' tired of this unresolved point & tired to look-up up through `cron.daily` to see which par failed, I'll give it a shot; thanks for pointing out the mails on debian-devel

**Comment by a-detiste** [comment]
Hi, uploaded today to Debian + commented on on debian-devel mailing list.
https://tracker.debian.org/news/1438391/accepted-systemd-cron-11521-1-source-into-unstable/
