### ISSUE TITLE
`crontab -e` fails to update crontab

### ISSUE THREAD

**Issue by msva** [systemd-cron/systemd-cron#52]
I've found an issue, that when user has direct access to read/write crontab file (i.e. `crontab.py` doesn't fallback to setgid wrapper), it is an issue about properly writing crontab content (probably, side effect of fix of #39).

The issue is in that fact, that in that code:
```python
    tmp.file.flush()

    if subprocess.call([EDITOR, tmp.name]) != 0:
        tmp.close()
        sys.exit('edit aborted, your edit is kept here:%s' % tmp.name)

 <...>
    tmp.file.seek(0)
```

At the time of `seek` call, `tmp` still contains "old" content of the file (that was before opening `EDITOR`). So, all the changes made in `EDITOR` wasn't written in the user's crontab.
So, `tmp` needs to reload content before making the magic with `new`, `rename` and so on 🙂 

And #53 is a Pull Request with fix, that I tested locally.

**Comment by a-detiste** [comment]
Hi,

Thank you very much.
I reworked it even a bit more afterwards.

I think I remember that `delete=False` was added as as an aftertought and it shows.
