### ISSUE TITLE
cron-after-var.service hard-codes wrong path to systemctl

### ISSUE THREAD

**Issue by haasn** [systemd-cron/systemd-cron#54]
```
Sep 12 05:03:28 xor systemd[1]: Starting Rerun systemd-crontab-generator because /var is a separate mount...
Sep 12 05:03:28 xor sh[5354]: /bin/sh: 1: /usr/bin/systemctl: not found
Sep 12 05:03:28 xor sh[5354]: /bin/sh: 1: /usr/bin/systemctl: not found
Sep 12 05:03:28 xor systemd[1]: cron-after-var.service: Main process exited, code=exited, status=127/n/a
Sep 12 05:03:28 xor systemd[1]: Failed to start Rerun systemd-crontab-generator because /var is a separate mount.
Sep 12 05:03:28 xor systemd[1]: cron-after-var.service: Unit entered failed state.
Sep 12 05:03:28 xor systemd[1]: cron-after-var.service: Failed with result 'exit-code'.
```

Making a symlink /usr/bin/systemctl -> /bin/systemctl works around this bug. IMO it shouldn't assume systemctl is available in /usr/bin.

**Comment by kstep** [comment]
What do you propose?

**Comment by a-detiste** [comment]
Hi,

It's not harcoded, "@bindir@/systemctl", which is set by the configure script.

Moreover, the "bash -c" transaction encapsulation can now finally be removed.
https://bugs.freedesktop.org/show_bug.cgi?id=68878#c5

https://github.com/systemd/systemd/pull/5354

**Comment by haasn** [comment]
> It's not harcoded, "@bindir@/systemctl", which is set by the configure script.

Does that mean this is a packaging error?

**Comment by a-detiste** [comment]
I guess, which distro are you using ? Are you building from scratch?

**Comment by realnc** [comment]
Same issue here on Gentoo.

Gentoo tracker bug: https://bugs.gentoo.org/625400
