### ISSUE TITLE
Mail stdout regardless of failure

### ISSUE THREAD

**Issue by TheSin-** [systemd-cron/systemd-cron#55]
Could we have a switch or something to mail the output regardless of failure?  To be a true a cron replacement this is required, things like chkrootkit, debsums, rkhunter all send me info nightly, since switching I no longer get these.  This makes systemd-cron not a true replacement as it changes behaviour.  My personal cron jobs I started o wrap in mailx, but I can't do that for system cronjobs and I need to emails to properly maintain and monitor all my servers.

I'd be really nice if this became default again, if stdout then send to MAILTO, but even a switch would be nice.

**Comment by a-detiste** [comment]
Hi,

There are two way to do this:

- instead of ExecStart= 'ing the intended program direclty, use a wrapper instead.. but then systemctl / journalctl will see the wrapper instead of the actual command
or
- after job is done, in ExecStartPost= , run a tool that parse the journal and mails it's contents.
I prefer this way; but it was not that easy to implement, to just get last run log and not log from previous execution cobbled together, so it remained unimplemented

**Comment by TheSin-** [comment]
sadly I don't make the services, it's all Debian installed packages which I don't want to modify.

I'm just saying to truly replace current cron, I should be able to add to /etc/cron.d/blah, and have the output of blah email my support staff as this is what current cron does.  I really want to switch to a pure systemd alternative but I can not if I can't get things like the packages listed above to send emails on output.

**Comment by a-detiste** [comment]
for clarity systemd-cron purpose is to translate /etc/cron.d/blah into runtime services in /run/systemd (this is a tmpfs, they are rebuilt at each boot) we don't need to modify other packages' services files

it's also a stop gap until the packages provide blah.timer units, then the matching /etc/cron.d/blah unit is ignored

the stdout grabbing conflict with the OnError handler... I need to wrap my head around on how to avoid to get 2 or 1 mail but just one in all case of stdout or error code

**Comment by TheSin-** [comment]
correct, and I'm a systemd novice I'm just trying to learn it and convert to it.  So I'll be no help, I just know I'd like to systemd-cron instead of cron, but without those emails going to my ticketing system for my staff to be able to monitor and maintainer all the servers I just won't be able to.  Even if there was some sort of gable config file in /etc where eI could set MAILONERRORONLY=0 or something.

**Comment by a-detiste** [comment]
This could be mostly OK to do with a C/C++ wrapper hat would share code with mail_on_failure.
