### ISSUE TITLE
systemd-crontab-generator: "garbled time" for range in day of week field

### ISSUE THREAD

**Issue by alexbarton** [systemd-cron/systemd-cron#57]
This `crontab` entry:
```
10 7   * * 2-7   root   /usr/local/bin/testcmd
```

Produces the following error:
```
systemd-crontab-generator[…]: garbled time in /etc/cron.d/test [10 7 * * 2-7 root /usr/local/bin/testcmd]: 2-7
```

**Workaround**: Write the `contab` like this:
```
10 7   * * 2,3,4,5,6,7   root   /usr/local/bin/testcmd
```

So I think `systemd-crontab-generator` failed to parse the range in the day of week field?

(Tested with _systemd-cron 1.5.12_ on _Debian testing_.)

**Comment by a-detiste** [comment]
fixed in git
