### ISSUE TITLE
Email on failure gives python error

### ISSUE THREAD

**Issue by kolcon** [systemd-cron/systemd-cron#61]
Hello,

When a cron job fails, the notification email is not sent.

The fail notification sevice (ie. cron-failure@cron-lubos-lubos-0.service) fails on python errors.

eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.5
  [2]   python2.7

# emerge -pv systemd-cron

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sys-process/systemd-cron-1.5.12-r1::gentoo  USE="-cron-boot -etc-crontab-systemd -minutely -setgid {-test} -yearly" PYTHON_SINGLE_TARGET="python3_5 -pypy3 -python3_4 -python3_6" PYTHON_TARGETS="python3_5 -pypy3 -python3_4 -python3_6" 0 KiB

cron-failure@cron-lubos-lubos-0.service - systemd-cron OnFailure for cron-lubos-lubos-0
   Loaded: loaded (/lib/systemd/system/cron-failure@.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2018-06-08 07:50:03 CEST; 3 days ago
     Docs: man:systemd.cron(7)
 Main PID: 8098 (code=exited, status=1/FAILURE)

Jun 08 07:50:03 vhp mail_on_failure[8098]:   File "/usr/lib64/python3.5/subprocess.py", line 385, in run
Jun 08 07:50:03 vhp mail_on_failure[8098]:     stdout, stderr = process.communicate(input, timeout=timeout)
Jun 08 07:50:03 vhp mail_on_failure[8098]:   File "/usr/lib64/python3.5/subprocess.py", line 790, in communicate
Jun 08 07:50:03 vhp mail_on_failure[8098]:     stdout = self.stdout.read()
Jun 08 07:50:03 vhp mail_on_failure[8098]:   File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
Jun 08 07:50:03 vhp mail_on_failure[8098]:     return codecs.ascii_decode(input, self.errors)[0]
Jun 08 07:50:03 vhp mail_on_failure[8098]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal no>
Jun 08 07:50:03 vhp systemd[1]: cron-failure@cron-lubos-lubos-0.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 07:50:03 vhp systemd[1]: cron-failure@cron-lubos-lubos-0.service: Failed with result 'exit-code'.
Jun 08 07:50:03 vhp systemd[1]: Failed to start systemd-cron OnFailure for cron-lubos-lubos-0.

If I run it manually, ie. /usr/lib/systemd-cron/mail_on_failure cron-lubos-lubos-0, it works OK.
ENV is the same.

systemd version 
[ebuild   R    ] sys-apps/systemd-238-r7:0/2::gentoo  USE="acl cryptsetup gcrypt kmod lz4 pam pcre policykit seccomp split-usr ssl sysv-utils xkb -apparmor -audit -build -curl -elfutils -gnuefi -http -idn -importd -libidn2 -lzma -nat -qrcode (-selinux) {-test} -vanilla" ABI_X86="32 (64) (-x32)" 0 KiB

**Comment by a-detiste** [comment]
Hi, this should be solved by 76de66bb0f32ee08d7a38edd42ac9d5d6d2301d8
