### ISSUE TITLE
Slight problem with generator (systemd itself?)

### ISSUE THREAD

**Issue by Shea690901** [systemd-cron/systemd-cron#62]
I'm using Lubuntu 18.04 and changed from anacron to systemd-cron.
One of the old files within /etc/cron.d is 
```
53 *     * * * root if [ ! -d /run/systemd/system ] ; then ntpviz -p 1 -o /var/lib/ntp/ntpviz/day  @/etc/ntpviz/options 2> /dev/null ; find /var/lib/ntp/ntpviz/day  -type f -mtime +1 -delete ; fi
45 11,23 * * * root if [ ! -d /run/systemd/system ] ; then ntpviz -p 7 -o /var/lib/ntp/ntpviz/week @/etc/ntpviz/options 2> /dev/null ; find /var/lib/ntp/ntpviz/week -type f -mtime +7 -delete ; fi
*/5 *    * * * root [ ! -d /run/systemd/system ] && [ -e /run/gpsd.sock ] && [ -x /usr/sbin/ntploggps ] && /usr/sbin/ntploggps -o -l /var/log/ntpstats/gpsd 2> /dev/null
*/5 *    * * * root [ ! -d /run/systemd/system ] && [ -x /usr/sbin/ntplogtemp ] && /usr/sbin/ntplogtemp -o -l /var/log/ntpstats/temps
```
All timer units are generated as expected.
BUT:
This generates every 5min a mail that the unit for ```[ ! -d /run/systemd/system ] && [ -e /run/gpsd.sock ] && [ -x /usr/sbin/ntploggps ] && /usr/sbin/ntploggps -o -l /var/log/ntpstats/gpsd 2> /dev/null``` couldn't be started (I don't have anything gps related installed, as such /run/gpsd.sock doesn't exist).

As a workaround I've added a ``` || exit 0``` to the offending command, but I think something should be done to the generator instead.

**Comment by kstep** [comment]
I guess the command returns non-zero exit code. I don't know how generator can tell non-zero exit code as an error, and as not an error. So your "workaround" is actually the right solution for your case.

**Comment by Shea690901** [comment]
Rather old (and for me not realy relevant anymore), but when going over my notifications I found this one and got an idea:
Every cron command has to be able to be run by `sh`, so why not integrate a parser that may detect standard tests and reformulate them for systemd?
This way one could generate a unit for the above example similar to this:
~~~
[Unit]
Description=*/5 *    * * * root [ ! -d /run/systemd/system ] && [ -e /run/gpsd.sock ] && [ -x /usr/sbin/ntploggps ] && /usr/sbin/ntploggps -o -l /var/log/ntpstats/gpsd 2> /dev/null
ConditionPathExists=/run/gpsd.sock
ConditionFileIsExecutable=/usr/sbin/ntploggps

[Service]
Type=oneshot
IgnoreSIGPIPE=false
User=root
StandardError=/dev/null
ExecStart=/usr/sbin/ntploggps -o -l /var/log/ntpstats/gpsd
~~~

**Comment by a-detiste** [comment]
Here it should generate nothing at all.

( test -d /run/systemd).

I tried already but it would be fragile


Le dim. 20 févr. 2022 à 16:51, Shea690901 ***@***.***> a
écrit :
