### ISSUE TITLE
Add KillMode=process option.

### ISSUE THREAD

**Issue by Debilski** [systemd-cron/systemd-cron#64]
Currently, all cron units will be run with `KillMode=control-group` (the default; see here: https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode= ). This has the effect that once the main executable exits, all child processes in the cgroup are killed automatically.
Specifically, if we add a script to our crontab that uses a tools like `s-nail` to send mails asynchronously, the mail will not be sent, when we have `s-nail` in the last line of our script.

I suggest adding a possibility to have a cron unit run with `KillMode=process`, which keeps the subprocesses around even when the main process exits.

**Comment by a-detiste** [comment]
Hi,
This seems to make sense, applied
