### ISSUE TITLE
Jobs running as root do not have USER, LOGNAME, HOME or SHELL set

### ISSUE THREAD

**Issue by tumd** [systemd-cron/systemd-cron#65]
In commits f0fdf82 and 7d7cdb3 the above variables was removed, and 'User' is not set in the generated systemd-service when root is set to run a cronjob.

systemd.exec(5) says:
> $USER, $LOGNAME, $HOME, $SHELL
>  ... The variables are set for the units that have User= set, which includes user systemd instances.

This means these variables are __never__ present in the job's environment, on root-owned jobs.

For me this created problems in one of my self-made scripts. It was easy fixed in my script, but still - it wasn't a problem when running vixie cron, thus I believe this is a bug?

Debian Stretch (9.6)
systemd 232-25+deb9u6
systemd-cron 1.5.8-1

**Comment by a-detiste** [comment]
I'm not sure about systemd.exec(5) anymore, better try by experiment.
And what about the static jobs (hourly/daily/weekly/monthly ?)

**Comment by a-detiste** [comment]
this will be fixed in next upload
