### ISSUE TITLE
systemd-cron hates non english characters.

### ISSUE THREAD

**Issue by Swiftyhu** [systemd-cron/systemd-cron#68]
I upgraded my Debian box from cron to systemd-cron. Unfortunately the new cron daemon stopped to work.

I had some hungarian characters in my old crontab. Funnily enough these characters were in the comments.

Error when I tried to see the crontab with systemd-cron:

` # crontab -l`
`Traceback (most recent call last):`
`  File "/usr/bin/crontab", line 340, in <module>`
`    action(cron_file, args)`
`  File "/usr/bin/crontab", line 118, in list`
`    sys.stdout.write(f.read())`
`  File "/usr/lib/python3.7/codecs.py", line 322, in decode`
`    (result, consumed) = self._buffer_decode(data, self.errors, final)`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1103: invalid continuation byte`

And the actual line of problem:
`#dow 0-6 0=Vasárnap 1=Hétfő 2=Kedd 3=Szerda 4=Csütörtök 5=Péntek 6=Szombat`

(The days of week in Hungarian.)

**Comment by trentbuck** [comment]
Hi, I'm a nosy bystander.
Was your crontab encoded in UTF-8, or a legacy encoding like ISO-8859-2?
systemd-cron is mostly "assume UTF-8" which it inherits from Python.

If I paste your example into a text file, I can use iconv(1) to convert and file(1) to check:

    $ cat >x
     #dow 0-6 0=Vasárnap 1=Hétfő 2=Kedd 3=Szerda 4=Csütörtök 5=Péntek 6=Szombat
    $ file x
    x: UTF-8 Unicode text
    $ iconv --to iso-8859-3 x
     #dow 0-6 0=Vas�rnap 1=H�tficonv: illegal input sequence at position 29
    $ iconv --to iso-8859-2 x
     #dow 0-6 0=Vas�rnap 1=H�tf� 2=Kedd 3=Szerda 4=Cs�t�rt�k 5=P�ntek 6=Szombat
    $ iconv --to iso-8859-2 x | file -
    /dev/stdin: ISO-8859 text

**Comment by Swiftyhu** [comment]
Hi @trentbuck !

I do not really know. To be honest, I changed back to cron daemon and removed the hungarian characters too...
But I think it was all legacy ISO-8859-2.

I do not know the inner workings of systemd-cron, but I expected that it ignores every comment it can find... :)

**Comment by a-detiste** [comment]
No hate here, just love <3 . I'm sorry I think python may be not the right language for systemd-cron (original author kstep did a fork in Rust). My plan on Debian was to simply use the `crontab` for Vixie Cron, but it did not happened.
Python will always be more brittle than C when working with unexpected non UTF8 files.

![image](https://user-images.githubusercontent.com/7994192/152076091-3a5d3f4f-8800-4daf-b5a4-3da99c1f20ce.png)

**Comment by a-detiste** [comment]
Done
