### ISSUE TITLE
OnFailure should not be created with MAILTO=

### ISSUE THREAD

**Issue by rlaager** [systemd-cron/systemd-cron#69]
https://github.com/systemd-cron/systemd-cron/blob/707d1cef53d1b66c9ffbdd61ca62640637f07adb/src/bin/systemd-crontab-generator.py#L458

`if '"MAILTO="' in job['e']:` should be `if 'MAILTO=' in job['e']:`

The double-quoting is wrong and breaks this. That is, if I have a cron file like this:
```
MAILTO=
... some cron job ...
```

I am expecting no `OnFailure`, but I am getting one.

**Comment by a-detiste** [comment]
Hi, indeed, this broke when we introduced `environment_string()`

**Comment by rlaager** [comment]
@a-detiste The fix to this is trivial (pull request #70). Any chance you could merge that?
