### ISSUE TITLE
My system won't reach multi-user.target with systemd-cron

### ISSUE THREAD

**Issue by bowlofeggs** [systemd-cron/systemd-cron#72]
Greetings!

I don't know enough details to fully debug this issue, so I will just describe what I'm seeing. When I boot my system (Gentoo with `systemd-247_rc2`) with this package installed (`1.5.15`), it doesn't reach `graphical.target` or `multi-user.target`. It does reach `basic.target`, but then stops that target as well.

In the journal, I see messages about how it's detected that I have a separate `/var` (I do), and that it's going to do a reload as a result. Here are some log lines that I believe are relevant (I've trimmed out a lot of noise):

```
Nov 19 19:41:09 host.example.com systemd[1]: Reached target systemd-cron.
Nov 19 19:41:09 host.example.com systemd[1]: Reached target Timers.
Nov 19 19:41:09 host.example.com systemd[1]: Reached target Basic System.
Nov 19 19:41:09 host.example.com systemd[1]: Starting Rerun systemd-crontab-generator because /var is a separate mount...
Nov 19 19:41:09 host.example.com systemd[1]: Reloading.
Nov 19 19:41:09 host.example.com systemd[1]: cron-after-var.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Nov 19 19:41:09 host.example.com systemd[1]: Stopped target Local File Systems.
Nov 19 19:41:09 host.example.com systemd[1]: Unmounting /boot...
Nov 19 19:41:09 host.example.com systemd[1]: Unmounting /home...
Nov 19 19:41:09 host.example.com systemd[1]: Started systemd-cron daily timer.
Nov 19 19:41:09 host.example.com systemd[1]: Started systemd-cron hourly timer.
Nov 19 19:41:09 host.example.com systemd[1]: Started systemd-cron monthly timer.
Nov 19 19:41:09 host.example.com systemd[1]: Started systemd-cron weekly timer.
Nov 19 19:41:09 host.example.com systemd[1]: Reached target systemd-cron.
Nov 19 19:41:09 host.example.com systemd[1]: cron-after-var.service: Succeeded.
Nov 19 19:41:09 host.example.com systemd[1]: Started cron-after-var.service.
Nov 19 19:41:09 host.example.com systemd[1]: Stopped target Basic System.
```

After this, `/home` is never remounted and as a result, `basic.target` is also never reached. This causes many other units not to start on the system, of course.

I'm not sure why this is happening, but that log message about a command that has vanished from the unit file seems like a good thing to focus on.

**Comment by bowlofeggs** [comment]
I found https://github.com/systemd/systemd/issues/16076, which discusses problems with using relative paths in systemd units, such as `systemctl`. I see that this is happening here:

https://github.com/systemd-cron/systemd-cron/blob/0d05ae08d985685ca61ddefec3df5d1406651e14/src/bin/systemd-crontab-generator.py#L621

That may be the problem.

**Comment by charles-dyfis-net** [comment]
To speak to this a little --

As a `daemon-reload` serializes and deserializes systemd's state, doing one while that state is actively changing tends to be a trigger for potential bugs (in places assume that transitions through the state machine won't involve the underlying system's state changing while systemd is unable to actively monitor and account for those changes).

**Comment by a-detiste** [comment]
The `daemon-reload` is needed to ask `systemd` to rerun `systemd-crontab-generator` a _second time_ after `/var` had become available.
