### ISSUE TITLE
Special user nobody configured, this is not safe!

### ISSUE THREAD

**Issue by daviessm** [systemd-cron/systemd-cron#73]
With systemd-246

systemd reports in the journal:

    Dec 25 14:14:40.461551 localhost systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!

Should the service run as a different user?

**Comment by mmirate** [comment]
A web search yields the following: https://github.com/systemd/systemd/commit/bed0b7dfc0070e920d00c89d9a4fd4db8d974cf0

**Comment by a-detiste** [comment]
fixed in https://github.com/systemd-cron/systemd-cron/commit/be4aea647bce9a0f26c9b8126f7883dd5c0b60a2
