### ISSUE TITLE
OnFailure will not be added when MAILTO is used.

### ISSUE THREAD

**Issue by MarcoCLA** [systemd-cron/systemd-cron#79]
This happens to be a very old bug
Commit 6dd6957fd86cb83e647a0792e5274b03e91cbc52 introduced a bug related to the initiation of the OnFailure service (this code was introduced in 2081ca9c21524f89355b1c205a2776b55e7bf332)

A attempt to to fix the issue was done by commit 0d05ae08d985685ca61ddefec3df5d1406651e14, however this skips adding OnFailure when MAILTO **is** present.

Edit: apparently 123d6c8f3d013121cbe34725d4a084b6e7bd5d0f already broke it.

What is the expected behaviour? 

-  Disabling mailto by adding `"MAILTO="`
-  Disabling mailto by adding `MAILTO=""`
-  Disabling mailto by adding `MAILTO=`

**Comment by a-detiste** [comment]
thanks

**Comment by a-detiste** [comment]
you're getting a good grip of this

> Disabling mailto by adding MAILTO=""
> Disabling mailto by adding MAILTO=

I think it's what original cron does

**Comment by a-detiste** [comment]
this propose use of shlex.split()

https://github.com/systemd-cron/systemd-cron/pull/74/commits/572f584420204f8e37c5adc18cb9c5e97b6aa76e

**Comment by a-detiste** [comment]
I'd like to test/fix proposal from https://github.com/systemd-cron/systemd-cron/issues/75 and make a release
