### ISSUE TITLE
systemd-crontab-generator doesn't have a way to disable /etc/cron.d units

### ISSUE THREAD

**Issue by scolby33** [systemd-cron/systemd-cron#81]
The Debian `cron(8)` applies the rules of `run-parts` to file names in `/etc/cron.d`. (https://manpages.debian.org/bullseye/cron/cron.8.en.html). For example, that means that `/etc/cron.d/foo.disabled` will be ignored because of the `.` in the name.

`systemd-crontab-generator` does not follow this pattern, which means there isn't an obvious way for an administrator to prevent `systemd-crontab-generator` from creating a timer for certain cron configurations.

Some files are already ignored: 
https://github.com/systemd-cron/systemd-cron/blob/c9b413aa3b46ceaab4a924a3ade03f4da0103edc/src/bin/systemd-crontab-generator.py#L542-L549

However, I don't want to make the files I want to disable hidden, contain a `~`, or squat on the `.dpkg-` namespace.

Thus, I propose adding another check like:
```python
        if basename.endswith('.disabled'):
            log(5, 'ignoring %s' % filename)
            continue
```

If this seems reasonable, I am happy to open a PR. I am also happy to have this code pulled in by an existing owner, since it is so simple.

**Comment by a-detiste** [comment]
Hi,

You can also use `systemctl mask something.timer` to mask the job.

**Comment by scolby33** [comment]
Now, that's an idea I hadn't even considered. Thank you!
