### ISSUE TITLE
Release v1.5.18 is tagged 1.15.18

### ISSUE THREAD

**Issue by rich0** [systemd-cron/systemd-cron#82]
The documentation for the latest release suggests it is intended to be v1.5.18, which is logical based on the current scheme.  However, the tag itself is marked 1.15.18.

Various distros have adopted one version vs the other:
https://repology.org/project/systemd-cron/versions

You might want to take some action to make the versions consistent, or otherwise take this into account in future versioning as some distros may run into issues with ordering.

**Comment by a-detiste** [comment]
Ok publishing a new release
