### ISSUE TITLE
crontab -e fails if $EDITOR is set with arguments

### ISSUE THREAD

**Issue by fran-penedo** [systemd-cron/systemd-cron#83]
`subprocess.call` will fail with `FileNotFoundError: [Errno 2] No such file or directory: 'emacsclient -s daemon'`.

In https://github.com/systemd-cron/systemd-cron/blob/c9b413aa3b46ceaab4a924a3ade03f4da0103edc/src/bin/crontab.py#L191, split `EDITOR` by whitespace:

``` python
    if subprocess.call(EDITOR.split(" ") + [tmp.name]) != 0:
```

**Comment by a-detiste** [comment]
thanks, fixed in #[1ae911b](https://github.com/systemd-cron/systemd-cron/commit/1ae911bc30c529c8ba20969c39c26eb1f278d5c6)

**Comment by a-detiste** [comment]
@nabijaczleweli important

**Comment by nabijaczleweli** [comment]
Works in crontab.cpp, I used `EDITOR='truncate -s0' crontab -e` and `EDITOR='rm -vf' crontab -e` while testing
