### ISSUE TITLE
how to make systemd-cron more cron-alike?

### ISSUE THREAD

**Issue by harridu** [systemd-cron/systemd-cron#84]
Hi folks,

it is not uncommon that a cron job fails. Usually you don't add if statements to your crontab entry, but something like this
```
	42 * * * *	some_silent_check && process_something
```
Using the traditional cron this was never an issue. Using systemd-cron the monitoring system goes nuts because suddenly there are a bazillion of failed service entries.

Would it be possible to avoid this somehow without editing all cron jobs for all users on all hosts using systemd-cron?

And a related issue: If I remove a cron job then systemd complains
```
# systemctl --failed
  UNIT                           LOAD      ACTIVE SUB    DESCRIPTION
* cron-username-username-8.service not-found failed failed cron-username-username-8.service
* cron-username-username-8.timer   not-found failed failed cron-username-username-8.timer

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
2 loaded units listed.
```
systemd-cron is version 1.5.16-1, as it can be found in Debian 11.

Regards
Harri

**Comment by a-detiste** [comment]
Maybe adding "|| true" ?
