### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by koraa** [systemd-cron/systemd-cron#91]
Thank you for writing systemd-cron. It is wonderful to be able to use my existing cron jobs with cron. :pray: 

I just faced an issue when adding a new crontab file (/etc/cron.d): no cron jobs were added to the systemd timer list.

Running the generator manually revealed a hard-to-understand syntax error (details below). Correcting the syntax error resolved the issue.

To improve the robustness of systemd-cron, please consider implementing a more graceful error handling process, which includes:

- [ ] Providing error output that specifically points out parsing issues
- [ ] Supplying debug output (potentially via journalctl)
- [ ] Introducing a command to specifically reload cron jobs with error reporting
- [x] Ensuring other cron jobs load even when a single file fails to parse

```
/usr/lib/systemd/system-generators/systemd-crontab-generator /tmp/foo
Traceback (most recent call last):
  File "/usr/lib/systemd/system-generators/systemd-crontab-generator", line 652, in <module>
    main()
  File "/usr/lib/systemd/system-generators/systemd-crontab-generator", line 554, in main
    generate_timer_unit(job, seq=seqs.setdefault(job['j']+job['u'], count()))
  File "/usr/lib/systemd/system-generators/systemd-crontab-generator", line 425, in generate_timer_unit
    with open('%s/%s.sh' % (TARGET_DIR, unit_name), 'w', encoding='utf8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/foo/cron-nextcloud-/containers/cont.sh-0.sh'
```

**Comment by a-detiste** [comment]
Please provide the affected crontab. (name & content)

**Comment by a-detiste** [comment]
The jobid cleansing might solve your issue ... I need more info.

```
VALID_CHARS = "-_" + string.ascii_letters + string.digits
self.jobid = ''.join(c for c in self.jobid if c in VALID_CHARS)
```

**Comment by koraa** [comment]
I no longer have the crontab file…it was a fairly basic mistake; I think I omitted the user name column…

The tool was right to complain about the file; this was a real syntax error. What needs fixing is the usability aspect.

**Comment by a-detiste** [comment]
This is now addressed in individual by-topic issues
