### ISSUE TITLE
unknown schedule error since 1.16.1

### ISSUE THREAD

**Issue by todi** [systemd-cron/systemd-cron#94]
After upgrading from 1.15.22 to 1.16.1, after using `crontab -e` I get the following error for a crontab entry that was working before:

```
> crontab -e
crontab: unknown schedule in /tmp/crontab_am4tl66n: 0 23 * * * /usr/local/bin/learn_spam
not replacing crontab, your edit is kept here:/tmp/crontab_am4tl66n
```

I'm on Arch and I'm using the AUR package, if that makes a difference.

**Comment by a-detiste** [comment]
Thanks, I'm publishing an update now.
